### ISSUE TITLE
Wascap  is it standard ?

### ISSUE THREAD

**Issue by joeblew99** [waxosuit/wascap-codec#1]
Love the sandboxing idea.
But is there any progress on making it standard.

Saw reference to standards here:
https://wascap.io/faq/

this is very cool btw !!

**Comment by autodidaddict** [comment]
yes, Wascap is a standard. There aren't many folks using it yet because it's only been publicly available for a few weeks. However, if you check out [wapm.io](https://wapm.io) you'll see that Wascap is one of the interfaces (along with WASI) supported by that registry site.  I created an echo server and have published it on wapm.io. you can see their page for showing all of the uploaded `Wascap` modules [here](https://wapm.io/interface/wascap)

**Comment by autodidaddict** [comment]
@joeblew here's Wasmer's article that includes a mention of the Wascap interface: [https://medium.com/wasmer/introducing-webassembly-interfaces-bb3c05bc671](https://medium.com/wasmer/introducing-webassembly-interfaces-bb3c05bc671)

**Comment by autodidaddict** [comment]
Closing this issue as we've been discussing this via e-mail.
